{
  config,
  lib,
  ...
}:
let
  cfg = config.services.acuttis-point;

  timeType = lib.types.strMatching "([01][0-9]|2[0-3]):[0-5][0-9]";

  dateType = lib.types.strMatching "[0-9]{4}-[0-9]{2}-[0-9]{2}";

  weekdayType = lib.types.enum [
    "MON"
    "TUE"
    "WED"
    "THU"
    "FRI"
    "SAT"
    "SUN"
  ];

  boolean = value: if value then "true" else "false";
in
{
  options.services.acuttis-point = {
    enable = lib.mkEnableOption "the Acuttis timekeeping automation";

    package = lib.mkOption {
      type = lib.types.package;
      description = "The acuttis-point package to run.";
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "acuttis-point";
      description = "User the automation runs as.";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "acuttis-point";
      description = "Group the automation runs as.";
    };

    # The schedule is declared once, here: the service reads it as environment
    # variables and the timer turns the same times into OnCalendar entries, so
    # the two cannot drift apart.
    schedule = {
      entry = lib.mkOption {
        type = timeType;
        example = "08:00";
        description = "Time the first punch of the day is due.";
      };

      lunchStart = lib.mkOption {
        type = timeType;
        example = "12:00";
        description = "Time the lunch break punch is due.";
      };

      lunchEnd = lib.mkOption {
        type = timeType;
        example = "14:00";
        description = "Time the return from lunch punch is due.";
      };

      exit = lib.mkOption {
        type = timeType;
        example = "17:30";
        description = "Time the last punch of the day is due.";
      };
    };

    workDays = lib.mkOption {
      type = lib.types.nonEmptyListOf weekdayType;
      default = [
        "MON"
        "TUE"
        "WED"
        "THU"
        "FRI"
      ];
      description = "Days the automation may act on.";
    };

    toleranceMinutes = lib.mkOption {
      type = lib.types.ints.between 0 240;
      default = 10;
      description = ''
        How many minutes after a scheduled time a punch may still be registered.
        Outside this window a run aborts instead of registering a time that no
        longer reflects reality, which is also what makes a catch-up run after a
        suspend safe.
      '';
    };

    minLunchMinutes = lib.mkOption {
      type = lib.types.ints.between 0 480;
      default = 60;
      description = ''
        The shortest lunch break the schedule is allowed to be able to produce.
        A floor rather than a target: a schedule whose worst case falls under it
        is refused at build time.

        The worst case is both windows going the wrong way at once — the punch
        leaving for lunch landing as late as its tolerance allows, and the one
        returning landing as early as its own. One hour is the legal minimum in
        Brazil for a working day over six hours.
      '';
    };

    timezone = lib.mkOption {
      type = lib.types.str;
      default = "America/Sao_Paulo";
      description = "IANA timezone the schedule is written in.";
    };

    skipDates = lib.mkOption {
      type = lib.types.listOf dateType;
      default = [ ];
      example = [ "2026-09-07" ];
      description = "Holidays, vacation and other days without an expedient.";
    };

    dryRun = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Decide and log, but never register a punch.";
    };

    jitterSeconds = lib.mkOption {
      type = lib.types.ints.between 0 3600;
      default = 0;
      example = 540;
      description = ''
        Spread each punch randomly over this many seconds after its scheduled
        time, so the day is not registered to the same minute twice.

        systemd can only delay, never bring forward, which decides how the
        schedule has to be written: set `schedule.entry` and `schedule.lunchEnd`
        this many seconds earlier than the times actually wanted, and they land
        at or before them while `lunchStart` and `exit` land at or after theirs.
        Worked time then only ever comes out at or above the nominal day.

        Must not exceed `toleranceMinutes`, or a delayed run would arrive after
        its own window had closed and refuse to register anything.
      '';
    };

    punchListSelector = lib.mkOption {
      type = lib.types.nullOr lib.types.nonEmptyStr;
      default = null;
      example = "div.styles_containerMarkingAddress__lLpPc";
      description = ''
        Selector matching one row per punch on the Acuttis receipt, across every
        day it lists. Null keeps the application's own default, which was read
        from the live site.

        Worth overriding when that default stops matching: its class is
        generated by CSS modules and will not survive an Acuttis frontend
        rebuild. That is survivable rather than dangerous — no rows at all is
        reported as an interface change, not as a day that never started — and
        `DISCOVER=true` finds the replacement.
      '';
    };

    environmentFile = lib.mkOption {
      type = lib.types.path;
      example = "/run/secrets/acuttis-point";
      description = ''
        File holding ACUTTIS_USERNAME and ACUTTIS_PASSWORD, read by systemd at
        start. Point this at a sops-nix or agenix secret; it must not be a path
        inside the Nix store, which is world readable.
      '';
    };

    notifyUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "https://ntfy.sh/something-random";
      description = ''
        Where to POST a push notification for each run. Shaped for ntfy. On the
        public server the topic name is the only thing protecting it, so use a
        random one — and note the message names the punch and its time, so it
        reaches that server in the clear.

        For a topic that should not sit in the world-readable Nix store, put
        NOTIFY_URL in `environmentFile` instead of here.
      '';
    };

    notifyOn = lib.mkOption {
      type = lib.types.enum [
        "always"
        "action"
        "problem"
      ];
      default = "action";
      description = ''
        Which runs are worth a phone buzzing. `action` stays silent when there
        was nothing to do, which is the common case after a manual punch.
      '';
    };

    screenshots = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Photograph the page when a run breaks — it is the only witness to an
        interface that changed. A refusal is not photographed: that is a
        decision rather than a malfunction.

        The punch modal shows a full name and a CPF, so the files are personal
        data. They live in the service's private state directory, mode 0600.
      '';
    };

    logFile = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "/var/lib/acuttis-point/runs.log";
      description = ''
        File the block-formatted run records are appended to. The one-line form
        always goes to the journal. Set to null to keep only the journal; a path
        outside the state directory needs its own ReadWritePaths entry.
      '';
    };

    extraEnvironment = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        PUNCH_TRIGGER_SELECTOR = "button.open-punch";
      };
      description = "Extra environment variables, for the remaining selectors.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = !lib.hasPrefix builtins.storeDir (toString cfg.environmentFile);
        message = ''
          services.acuttis-point.environmentFile must not be in the Nix store:
          everything there is world readable.
        '';
      }
      {
        assertion =
          let
            minutes = time: lib.toInt (lib.substring 0 2 time) * 60 + lib.toInt (lib.substring 3 2 time);
            guaranteed =
              minutes cfg.schedule.lunchEnd - minutes cfg.schedule.lunchStart - cfg.toleranceMinutes;
          in
          guaranteed >= cfg.minLunchMinutes;
        message = ''
          services.acuttis-point: this schedule could produce a lunch break
          shorter than minLunchMinutes (${toString cfg.minLunchMinutes}).
          The worst case is lunchStart landing ${toString cfg.toleranceMinutes}
          minutes late and lunchEnd landing on time. Move lunchEnd later,
          lunchStart earlier, or lower toleranceMinutes.
        '';
      }
      {
        assertion = cfg.jitterSeconds <= cfg.toleranceMinutes * 60;
        message = ''
          services.acuttis-point.jitterSeconds (${toString cfg.jitterSeconds})
          is longer than toleranceMinutes (${toString cfg.toleranceMinutes}),
          so a delayed run could arrive after its own window had closed and
          refuse to register anything.
        '';
      }
    ];

    users.users = lib.mkIf (cfg.user == "acuttis-point") {
      acuttis-point = {
        isSystemUser = true;
        group = cfg.group;
        description = "Acuttis timekeeping automation";
      };
    };

    users.groups = lib.mkIf (cfg.group == "acuttis-point") {
      acuttis-point = { };
    };

    systemd.services.acuttis-point = {
      description = "Register the timekeeping punch due now on Acuttis";
      # Started by the timer only. A punch outside its window is refused
      # anyway, so nothing is lost by not running at boot.
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      environment = {
        ENTRY_TIME = cfg.schedule.entry;
        LUNCH_START = cfg.schedule.lunchStart;
        LUNCH_END = cfg.schedule.lunchEnd;
        EXIT_TIME = cfg.schedule.exit;
        WORK_DAYS = lib.concatStringsSep "," cfg.workDays;
        TIME_TOLERANCE_MINUTES = toString cfg.toleranceMinutes;
        MIN_LUNCH_MINUTES = toString cfg.minLunchMinutes;
        TIMEZONE = cfg.timezone;
        SKIP_DATES = lib.concatStringsSep "," cfg.skipDates;
        DRY_RUN = boolean cfg.dryRun;
        HEADLESS = "true";
        NOTIFY_ON = cfg.notifyOn;
        # Keeps the session between runs, so four punches a day are not four
        # sign-ins. Stands in for the password until it expires, so it lives in
        # the private state directory and nowhere else.
        SESSION_FILE = "/var/lib/acuttis-point/session.json";
        # Chromium wants somewhere to put its profile and crash dumps.
        HOME = "/var/lib/acuttis-point";
      }
      // lib.optionalAttrs (cfg.punchListSelector != null) {
        PUNCH_LIST_SELECTOR = cfg.punchListSelector;
      }
      // lib.optionalAttrs (cfg.notifyUrl != null) { NOTIFY_URL = cfg.notifyUrl; }
      // lib.optionalAttrs cfg.screenshots {
        SCREENSHOT_DIR = "/var/lib/acuttis-point/screenshots";
      }
      // lib.optionalAttrs (cfg.logFile != null) { LOG_FILE = cfg.logFile; }
      // cfg.extraEnvironment;

      serviceConfig = {
        Type = "oneshot";
        ExecStart = lib.getExe cfg.package;
        EnvironmentFile = cfg.environmentFile;
        User = cfg.user;
        Group = cfg.group;
        StateDirectory = "acuttis-point";
        WorkingDirectory = "/var/lib/acuttis-point";

        # A refusal exits 2 and a failure exits 1, so both show the unit red,
        # which is the point: those are the runs that want a human.
        SuccessExitStatus = [ 0 ];

        NoNewPrivileges = true;
        PrivateTmp = true;
        ProtectHome = true;
        ProtectSystem = "strict";
        ProtectKernelTunables = true;
        ProtectControlGroups = true;
        RestrictSUIDSGID = true;
        # Chromium sandboxes itself with user namespaces and needs /dev/shm, so
        # the tighter sandboxing options are deliberately left off.
      };
    };

    environment.systemPackages = [ cfg.package ];
  };
}
