//// Where the automation touches the Acuttis page.
////
//// Acuttis is a client rendered application, so none of this can be derived
//// from a url. These selectors are configuration rather than constants,
//// because the ticket lists an interface change as a failure mode to survive
//// and swapping a selector should not mean editing Gleam.
////
//// Every default below was read from the live application while signed in.
//// The punch list one is the fragile one: its class is generated by CSS
//// modules, so it will stop matching when the Acuttis frontend is rebuilt.
//// That is survivable rather than dangerous, because the receipt lists several
//// days at once — a selector that stopped matching produces no rows at all,
//// which `acuttis.read_punches` tells apart from a day that has not started.
////
//// Three selectors can be set to nothing on purpose, which means "this step is
//// not needed here". That is how a deployment where the punches are already on
//// screen skips the clicking entirely.

import gleam/dict.{type Dict}
import gleam/string

pub type Selectors {
  Selectors(
    username_field: String,
    password_field: String,
    submit_button: String,
    /// Opens the punch interface. Empty means it is already open.
    punch_trigger: String,
    /// Present once the punch interface is open. Empty means nothing to wait
    /// for.
    punch_modal: String,
    /// Opens the receipt, the only place the punches are listed. Empty means
    /// they are already on screen.
    punch_receipt: String,
    /// Returns from the receipt to the punch controls. Empty means the controls
    /// never left.
    punch_back: String,
    /// Registers the punch.
    punch_button: String,
    /// Matches one row per punch on the receipt, across every day it lists.
    punch_list: String,
  )
}

// All read from the live application, signed in, on 2026-08-12.
const default_username_field = "input#username"

const default_password_field = "input#password"

const default_submit_button = "form.login-form button[type=submit]"

/// An anchor carrying the `touch_app` icon, not a button: the `modal-trigger`
/// class the public sign-in page uses does not exist once signed in.
/// The tooltip, not the class alone. On 2026-08-19 Acuttis added a second
/// `a.size-item-navbar` next to this one — a `settings_overscan` control — and
/// the class stopped identifying anything: the click went to whichever came
/// first and the modal never opened. Every run that day failed, all three
/// punches and all three rehearsals.
const default_punch_trigger = "a.size-item-navbar[data-tooltip=\"Marcar Ponto\"]"

const default_punch_modal = "#mark_modal"

const default_punch_receipt = "#mark_modal button:text-is(\"Comprovante de ponto\")"

const default_punch_back = "#mark_modal button:text-is(\"Voltar\")"

/// Exact text, not a substring: `has-text` would also match the neighbouring
/// "Comprovante de ponto", and matching the wrong control here is the one
/// mistake in this file that registers a punch.
const default_punch_button = "#mark_modal button:text-is(\"Ponto\")"

/// Generated by CSS modules, so it will not survive an Acuttis frontend
/// rebuild. `DISCOVER=true` finds the replacement.
const default_punch_list = "div.styles_containerMarkingAddress__lLpPc"

pub fn from_env(env: Dict(String, String)) -> Selectors {
  Selectors(
    username_field: or_default(env, "USERNAME_SELECTOR", default_username_field),
    password_field: or_default(env, "PASSWORD_SELECTOR", default_password_field),
    submit_button: or_default(env, "SUBMIT_SELECTOR", default_submit_button),
    punch_trigger: skippable(
      env,
      "PUNCH_TRIGGER_SELECTOR",
      default_punch_trigger,
    ),
    punch_modal: or_default(env, "PUNCH_MODAL_SELECTOR", default_punch_modal),
    punch_receipt: skippable(
      env,
      "PUNCH_RECEIPT_SELECTOR",
      default_punch_receipt,
    ),
    punch_back: skippable(env, "PUNCH_BACK_SELECTOR", default_punch_back),
    punch_button: or_default(env, "PUNCH_BUTTON_SELECTOR", default_punch_button),
    punch_list: or_default(env, "PUNCH_LIST_SELECTOR", default_punch_list),
  )
}

/// Blank falls back to the default: an empty value here is a half-filled
/// configuration file, not an instruction.
fn or_default(
  env: Dict(String, String),
  key: String,
  fallback: String,
) -> String {
  case dict.get(env, key) {
    Error(Nil) -> fallback
    Ok(value) ->
      case string.trim(value) {
        "" -> fallback
        trimmed -> trimmed
      }
  }
}

/// Presence decides instead: an unset key takes the default, but a key set to
/// nothing means the step it names is not needed.
fn skippable(
  env: Dict(String, String),
  key: String,
  fallback: String,
) -> String {
  case dict.get(env, key) {
    Error(Nil) -> fallback
    Ok(value) -> string.trim(value)
  }
}
